### ISSUE TITLE
"You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path."

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#389]
This is in my dev environment.  @arneec commented out STATIC_ROOT in the local settings file, was that an accident?  I'm going to turn it back on so I can keep developing.  If that's OK just mark this as completed.  Otherwise, please provide info how to resolve this problem, as there is no code comment explaining why it is turned off.

````
$ docker-compose up web
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
db is up-to-date
hackerspace_redis_1 is up-to-date
Starting hackerspace_web_1 ... done
Attaching to hackerspace_web_1
web_1          | ***** NO PRODUCTION SETTINGS FOUND     *******
web_1          | ***** IMPORTING LOCAL DEVELOPMENT SETTINGS         *******
web_1          | Traceback (most recent call last):
web_1          |   File "manage.py", line 11, in <module>
web_1          |     execute_from_command_line(sys.argv)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
web_1          |     utility.execute()
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 375, in execute
web_1          |     self.fetch_command(subcommand).run_from_argv(self.argv)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 323, in run_from_argv
web_1          |     self.execute(*args, **cmd_options)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 364, in execute
web_1          |     output = self.handle(*args, **options)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
web_1          |     collected = self.collect()
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
web_1          |     handler(path, prefixed_path, storage)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 342, in copy_file
web_1          |     if not self.delete_file(path, prefixed_path, source_storage):
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 249, in delete_file
web_1          |     if self.storage.exists(prefixed_path):
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/files/storage.py", line 310, in exists
web_1          |     return os.path.exists(self.path(name))
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/storage.py", line 44, in path
web_1          |     raise ImproperlyConfigured("You're using the staticfiles app "
web_1          | django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
hackerspace_web_1 exited with code 1
````

**Comment by tylerecouture** [comment]
Hmm... seems to actually be collecting the static files even in development, and now it's complaining that there are two of each of them.  It never did that before.

**Comment by tylerecouture** [comment]
My best guess (ignore me if I don't know what I'm talking about) is that there are still some production-specific settings in the docker-compose?  Either there is no need to collectstatic in development (django fakes it for us), or the local.py settings file needs to be set correctly:

Here's what happens when I uncomment 
`STATIC_ROOT = os.path.join(BASE_DIR, "static_in_project",  "static_root")` in local.py settings file:

```
web_1          | Found another file with the destination path 'admin/js/urlify.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
web_1          | Found another file with the destination path 'admin/js/core.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
```

**Comment by scssconsulting** [comment]
This happens because of collectstatic command. Remove that for dev docker compose.
