### ISSUE TITLE
New quests not becoming available as they should

### ISSUE THREAD

**Issue by mizzgoldberg** [timberline-secondary/hackerspace#400]
Completed first quest. It is pre-req for subsequent quests. Subsequent quests not appearing.

![Screenshot from 2020-04-09 14-15-09](https://user-images.githubusercontent.com/55294487/78941727-0e68e200-7a6d-11ea-9e7e-a3b2970f3ebd.png)
![Screenshot from 2020-04-09 14-15-18](https://user-images.githubusercontent.com/55294487/78941734-10cb3c00-7a6d-11ea-81a5-7e2404daece2.png)
![Screenshot from 2020-04-09 14-15-28](https://user-images.githubusercontent.com/55294487/78941735-1163d280-7a6d-11ea-9afa-1002ed2cd481.png)

**Comment by tylerecouture** [comment]
````
elery_1 | [2020-04-09 21:19:00,650: INFO/MainProcess] Received task: update_conditions_for_quest[ef36711b-7a29-4f2a-9dc0-484716661202]
db | ERROR: relation "quest_manager_quest" does not exist at character 1148
db | STATEMENT: SELECT "quest_manager_quest"."id", "quest_manager_quest"."name", "quest_manager_quest"."xp", "quest_manager_quest"."datetime_created", "quest_manager_quest"."datetime_last_edit", "quest_manager_quest"."short_description", "quest_manager_quest"."visible_to_students", "quest_manager_quest"."archived", "quest_manager_quest"."sort_order", "quest_manager_quest"."max_repeats", "quest_manager_quest"."repeat_per_semester", "quest_manager_quest"."hours_between_repeats", "quest_manager_quest"."date_available", "quest_manager_quest"."time_available", "quest_manager_quest"."date_expired", "quest_manager_quest"."time_expired", "quest_manager_quest"."icon", "quest_manager_quest"."verification_required", "quest_manager_quest"."hideable", "quest_manager_quest"."available_outside_course", "quest_manager_quest"."specific_teacher_to_notify_id", "quest_manager_quest"."campaign_id", "quest_manager_quest"."common_data_id", "quest_manager_quest"."instructions", "quest_manager_quest"."submission_details", "quest_manager_quest"."instructor_notes", "quest_manager_quest"."editor_id", "quest_manager_quest"."import_id", "quest_manager_quest"."blocking" FROM "quest_manager_quest" WHERE (NOT ("quest_manager_quest"."archived" = true) AND "quest_manager_quest"."id" = 1) ORDER BY "quest_manager_quest"."sort_order" DESC, "quest_manager_quest"."time_expired" DESC, "quest_manager_quest"."date_expired" DESC, "quest_manager_quest"."name" ASC LIMIT 1
celery_1 | [2020-04-09 21:19:00,702: ERROR/ForkPoolWorker-2] Task update_conditions_for_quest[ef36711b-7a29-4f2a-9dc0-484716661202] raised unexpected: ProgrammingError('relation "quest_manager_quest" does not exist\nLINE 1: ...import_id", "quest_manager_quest"."blocking" FROM "quest_man...\n ^\n',)
celery_1 | Traceback (most recent call last):
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celery_1 | return self.cursor.execute(sql, params)
celery_1 | psycopg2.errors.UndefinedTable: relation "quest_manager_quest" does not exist
celery_1 | LINE 1: ...import_id", "quest_manager_quest"."blocking" FROM "quest_man...
celery_1 | ^
celery_1 |
celery_1 |
celery_1 | The above exception was the direct cause of the following exception:
celery_1 |
celery_1 | Traceback (most recent call last):
celery_1 | File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
celery_1 | R = retval = fun(*args, **kwargs)
celery_1 | File "/usr/local/lib/python3.5/site-packages/celery/app/trace.py", line 650, in __protected_call__
celery_1 | return self.run(*args, **kwargs)
celery_1 | File "/app/src/prerequisites/tasks.py", line 49, in update_conditions_for_quest
celery_1 | quest = Quest.objects.filter(id=quest_id).first()
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 653, in first
celery_1 | for obj in (self if self.ordered else self.order_by('pk'))[:1]:
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 274, in __iter__
celery_1 | self._fetch_all()
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1242, in _fetch_all
celery_1 | self._result_cache = list(self._iterable_class(self))
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 55, in __iter__
celery_1 | results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1140, in execute_sql
celery_1 | cursor.execute(sql, params)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 99, in execute
celery_1 | return super().execute(sql, params)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
celery_1 | return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
celery_1 | return executor(sql, params, many, context)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celery_1 | return self.cursor.execute(sql, params)
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
celery_1 | raise dj_exc_value.with_traceback(traceback) from exc_value
celery_1 | File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
celery_1 | return self.cursor.execute(sql, params)
celery_1 | django.db.utils.ProgrammingError: relation "quest_manager_quest" does not exist
celery_1 | LINE 1: ...import_id", "quest_manager_quest"."blocking" FROM "quest_man...
celery_1 | ^
````
