### ISSUE TITLE
Importing badges doesn't set XP

### ISSUE THREAD

**Issue by tylerecouture** [timberline-secondary/hackerspace#496]
Importing and exporting occurs in django admin views uisng django-import-export package and ImportExportActionModelAdmin

**Comment by yujinyuz** [comment]
Could I get more details on this? I'm not sure where to start

**Comment by tylerecouture** [comment]
If you go to django admin, badges > badges,  Select a badge or a few, then in the admin actions (bottom) select "Export Selected Badges"  save them as a CSV.  Then go to another tenant, and in the same place, hit "Import (button at top right beside "add a badge" button.

Code for this is in badges/admin.py I think

**Comment by yujinyuz** [comment]
Just tried it and I'm getting errors when importing

```python
Errors
Line number: 2 - BadgeType matching query does not exist.
2, Pat on the back, 2016-07-05 23:01:19, 2016-07-05 23:01:58, You done did good!, , 3, , , 1
Traceback (most recent call last):
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 520, in import_row
self.import_obj(instance, row, dry_run)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 385, in import_obj
self.import_field(field, obj, data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 368, in import_field
field.save(obj, data, is_m2m)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/fields.py", line 110, in save
cleaned = self.clean(data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/fields.py", line 66, in clean
value = self.widget.clean(value, row=data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/widgets.py", line 364, in clean
return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
self.model._meta.object_name
badges.models.BadgeType.DoesNotExist: BadgeType matching query does not exist.

Line number: 3 - BadgeType matching query does not exist.
3, Treasure Hunter, 2016-07-05 23:01:20, 2016-07-05 23:01:59, You found something your teacher asked you to look for... like typos or broken links etc., , 3, , , 1
Traceback (most recent call last):
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 520, in import_row
self.import_obj(instance, row, dry_run)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 385, in import_obj
self.import_field(field, obj, data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/resources.py", line 368, in import_field
field.save(obj, data, is_m2m)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/fields.py", line 110, in save
cleaned = self.clean(data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/fields.py", line 66, in clean
value = self.widget.clean(value, row=data)
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/import_export/widgets.py", line 364, in clean
return self.get_queryset(value, row, *args, **kwargs).get(**{self.field: val})
File "/usr/local/var/pyenv/versions/hackerspace/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get
self.model._meta.object_name
badges.models.BadgeType.DoesNotExist: BadgeType matching query does not exist.
```

Can I confirm if this is also the same with the errors you've seen?

**Comment by tylerecouture** [comment]
Looks like the exported badge's badge.badge_type (foreign key) doesn't exist in your importing tenant.  Importing doesn't check most foreign keys.  Should probably handle that, but expected.

**Comment by yujinyuz** [comment]
Ahh. That's why. I'll try again with a prepopulated badge type and see what happens

**Comment by tylerecouture** [comment]
This stuff is not very robust, and kinda hacky, but it's used a lot! haha  I just whipped it together out of necessity
